# Cylane config file via .yaml
# Version 3.0
# You can use ${} to pass an enviroment varible from .env file
# Eg:
# something: ${DATA}

bot:
  TOKEN: Your token
  EMBED_COLOR: "#2b2d31"
  OWNER_ID: "Your id"
  LANGUAGE: en # You can set it to vi, en, th,...
  LIMIT_TRACK: 50 # The number of tracks you want to limit
  LIMIT_PLAYLIST: 20 # The number of playlist you want to limit

features:
  DATABASE:
    # Note: You can't enable all or 2 databases. It will return to JSON database
    JSON:
      enable: true
      path: "./cylane.database.json"
    MONGO_DB:
      enable: false
      # Your mongo_uri, you can get it from here: https://www.mongodb.com/
      uri: mongodb://127.0.0.1:27017/dreamvast
    MYSQL:
      enable: false
      host: "localhost"
      user: "me"
      password: "secret"
      database: "my_db"

  MESSAGE_CONTENT:
    enable: true
    prefix: "d!" # The prefix you want

  AUTO_DEPLOY: true
  AUTO_REMOVE_DUPLICATE: true
  AUTOFIX_LAVALINK: true # Fix the lavalink server when the current is down

  ALIVE_SERVER:
    enable: false
    port: 3000

  WEB_SERVER:
    enable: false # Must enable this before using ws
    port: 3000
    websocket:
      enable: false
      host: "0.0.0.0" # Default is 0.0.0.0
      secret: "-19023454588-0934825" # You must add your secret key to use ws. A secret key is anything you want
      auth: false
      trusted: ["http://localhost:3000"]

  # Your id or friend id (disable global command)
  DEV_ID: []
